import Head from "next/head";

import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { collection, getDocs, getFirestore } from "firebase/firestore";
import { app } from "@/firebase/config";
import { Container, ListContainer } from "@/styles/pages/home";
import ProductCard from "@/components/ProductCard";

interface Product {
  title: string;
  price: number;
  imgUrl: string;
}
const db = getFirestore(app);
export default function Home() {
  const [products, setProducts] = useState([]);

  async function fetchProducts(collec: string) {
    let result = null;
    let error = null;
    const collectionRef = collection(db, collec);

    try {
      result = await getDocs(collectionRef);

      const document: any = [];
      result.forEach((doc: any) => {
        document.push({
          ...doc.data(),
          id: doc.id,
        });
      });
      setProducts(document);
      console.log(document);

      //setProducts(result);
    } catch (e) {
      error = e;
    }
  }

  useEffect(() => {
    fetchProducts("products");
  }, []);

  return (
    <>
      <Head>
        <title>Cosmetic shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <ListContainer>
          {products.length > 0 &&
            products.map((prod: Product, i) => {
              return (
                <ProductCard
                  key={i}
                  title={prod.title}
                  price={prod.price}
                  imgUrl={prod.imgUrl}
                />
              );
            })}
        </ListContainer>
      </Container>
    </>
  );
}
